[project]
name = "circheck"
version = "0.1.0"
description = "Static analysis tool to detect ZKP vulnerabilities in Circom circuits."
authors = [{ name="Dang Duong Minh Nhat", email="dangduongminhnhat2003@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "antlr4-python3-runtime"
]

[project.scripts]
circheck = "circheck.cli:main"

[tool.setuptools]
packages = ["circheck"]
package-dir = {"" = "src"}

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
